<a href="https://colab.research.google.com/github/karodeakshat064/python90-/blob/main/Copy_of_Pandas_Exercise_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

use AUTOMOBILE DATASET

# New Section

Question 1: From given data set print first and last five rows

In [3]:
 # Importing the pandas library for data handling

import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [4]:
# Import pandas, read the CSV file into a DataFrame, and display the last 5 rows
import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.tail(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

Question 2: Clean data and update the CSV file
Replace all column values which contain ‘?’ and n.a with NaN.

In [5]:
# Read the CSV file, replace missing values (?, n.a) with NaN in selected columns, print the DataFrame, and save the cleaned data to a new CSV file
df = pd.read_csv("/content/sample_data/california_housing_train.csv", na_values={
'price':["?","n.a"],
'stroke':["?","n.a"],
'horsepower':["?","n.a"],
'peak-rpm':["?","n.a"],
'average-mileage':["?","n.a"]})
print (df)
df.to_csv("/content/cleaned_automobile_data.csv")

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]

Question 3: Find the most expensive car company name
Print most expensive car’s company name and price.

In [13]:
# Read the CSV file, select 'housing_median_age' and 'median_house_value' columns, filter the row with the maximum median_house_value, and display the result
import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df = df[['housing_median_age','median_house_value']][df.median_house_value==df['median_house_value'].max()]
df

       housing_median_age  median_house_value
215                  24.0            500001.0
260                  28.0            500001.0
862                  34.0            500001.0
1388                 40.0            500001.0
1404                 13.0            500001.0
...                   ...                 ...
16419                36.0            500001.0
16420                37.0            500001.0
16421                52.0            500001.0
16434                52.0            500001.0
16512                29.0            500001.0

[814 rows x 2 columns]

In [ ]:
# Question 4: Print All Toyota Cars details

In [14]:
# Read CSV file, group data by 'housing_median_age', and extract records for 'housing_median_age' of 15.0 into a new DataFrame
import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
car_Manufacturers = df.groupby('housing_median_age')
toyotaDf = car_Manufacturers.get_group(15.0)
toyotaDf

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
14,-114.63,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0
23,-114.98,33.82,15.0,644.0,129.0,137.0,52.0,3.2097,71300.0
38,-115.48,32.68,15.0,3414.0,666.0,2097.0,622.0,2.3319,91200.0
79,-115.56,32.80,15.0,1171.0,328.0,1024.0,298.0,1.3882,69400.0
...,...,...,...,...,...,...,...,...,...
16836,-123.34,39.50,15.0,2342.0,535.0,1064.0,433.0,1.8967,96600.0
16852,-123.48,40.79,15.0,619.0,160.0,287.0,104.0,1.9107,79200.0
16858,-123.58,39.66,15.0,1839.0,489.0,887.0,332.0,2.2429,100000.0
16957,-124.16,41.74,15.0,2715.0,569.0,1532.0,530.0,2.1829,69500.0
16983,-124.19,41.78,15.0,3140.0,714.0,1645.0,640.0,1.6654,74600.0

In [ ]:
#Question 5: Count total cars per company

In [15]:
# Read CSV file and count the number of occurrences of each 'housing_median_age' in the 'housing_median_age' column
import pandas as pd
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df['housing_median_age'].value_counts()

housing_median_age
52.0    1052
36.0     715
35.0     692
16.0     635
17.0     576
34.0     567
33.0     513
26.0     503
18.0     478
25.0     461
32.0     458
37.0     437
15.0     416
19.0     412
28.0     400
27.0     397
24.0     389
31.0     384
30.0     384
20.0     383
23.0     382
29.0     374
21.0     373
14.0     347
22.0     323
38.0     318
42.0     308
39.0     302
44.0     296
43.0     286
13.0     249
40.0     249
45.0     235
41.0     232
10.0     226
11.0     208
5.0      199
46.0     196
12.0     192
8.0      178
47.0     175
9.0      172
4.0      161
7.0      151
48.0     135
6.0      129
50.0     112
49.0     111
2.0       49
3.0       46
51.0      32
1.0        2
Name: count, dtype: int64

In [18]:
#Question 6: Find each company’s Higesht price car

In [16]:
# Read the CSV file, group data by 'housing_median_age', find the maximum 'median_house_value' for each 'housing_median_age', and print the result
import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_train.csv")

car_Manufacturers = df.groupby('housing_median_age')

priceDf = car_Manufacturers[['housing_median_age', 'median_house_value']].max()

print(priceDf)

                    housing_median_age  median_house_value
housing_median_age
1.0                                1.0            191300.0
2.0                                2.0            500001.0
3.0                                3.0            500001.0
4.0                                4.0            500001.0
5.0                                5.0            500001.0
6.0                                6.0            500001.0
7.0                                7.0            500001.0
8.0                                8.0            500001.0
9.0                                9.0            500001.0
10.0                              10.0            500001.0
11.0                              11.0            500001.0
12.0                              12.0            500001.0
13.0                              13.0            500001.0
14.0                              14.0            500001.0
15.0                              15.0            500001.0
16.0                              16.0            500001.0
17.0                              17.0            500001.0
18.0                              18.0            500001.0
19.0                              19.0            500001.0
20.0                              20.0            500001.0
21.0                              21.0            500001.0
22.0                              22.0            500001.0
23.0                              23.0            500001.0
24.0                              24.0            500001.0
25.0                              25.0            500001.0
26.0                              26.0            500001.0
27.0                              27.0            500001.0
28.0                              28.0            500001.0
29.0                              29.0            500001.0
30.0                              30.0            500001.0
31.0                              31.0            500001.0
32.0                              32.0            500001.0
33.0                              33.0            500001.0
34.0                              34.0            500001.0
35.0                              35.0            500001.0
36.0                              36.0            500001.0
37.0                              37.0            500001.0
38.0                              38.0            500001.0
39.0                              39.0            500001.0
40.0                              40.0            500001.0
41.0                              41.0            500001.0
42.0                              42.0            500001.0
43.0                              43.0            500001.0
44.0                              44.0            500001.0
45.0                              45.0            500001.0
46.0                              46.0            500001.0
47.0                              47.0            500001.0
48.0                              48.0            500001.0
49.0                              49.0            500001.0
50.0                              50.0            500001.0
51.0                              51.0            500001.0
52.0                              52.0            500001.0

In [19]:
#Question 7: Find the average mileage of each car making company

In [17]:
import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_train.csv")

mileageDf = df.groupby('housing_median_age')['median_income'].mean()

print(mileageDf)

housing_median_age
1.0     4.756800
2.0     5.074237
3.0     5.572013
4.0     5.196055
5.0     4.732460
6.0     4.463901
7.0     4.368441
8.0     4.412988
9.0     4.357513
10.0    4.126004
11.0    4.029663
12.0    4.003208
13.0    4.145092
14.0    4.148454
15.0    4.003953
16.0    4.288458
17.0    3.929201
18.0    3.954591
19.0    3.833244
20.0    3.749984
21.0    3.870417
22.0    3.941335
23.0    3.963371
24.0    3.921026
25.0    4.135890
26.0    4.071895
27.0    3.859375
28.0    3.813176
29.0    3.633556
30.0    3.580732
31.0    3.619995
32.0    3.800399
33.0    3.862161
34.0    3.959488
35.0    3.909391
36.0    3.973530
37.0    3.684131
38.0    3.463225
39.0    3.395865
40.0    3.432734
41.0    3.149125
42.0    3.447088
43.0    3.238897
44.0    3.507043
45.0    3.739467
46.0    3.357832
47.0    3.278638
48.0    3.526261
49.0    3.547657
50.0    3.472372
51.0    3.670503
52.0    3.943037
Name: median_income, dtype: float64

In [20]:
#Question 8: Sort all cars by Price column

In [11]:
 import pandas as pd

carsDf = pd.read_csv("/content/sample_data/california_housing_train.csv")

print(carsDf.columns)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [22]:
#Question 9: Concatenate two data frames using following conditions

# Create two data frames using following two Dicts, Concatenate those two data frame and create a key for each data frame.

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [23]:
import pandas as pd
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
carsDf1 = pd.DataFrame.from_dict(GermanCars)

In [25]:
#Question 10: Merge two data frames using following condition
# Create two data frames using following two Dicts, Merge two data frames, and append second data frame as a new column to first data frame.

Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [26]:
import pandas as pd
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
carPriceDf = pd.DataFrame.from_dict(Car_Price)
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
carsHorsepowerDf = pd.DataFrame.from_dict(car_Horsepower)
carsDf = pd.merge(carPriceDf, carsHorsepowerDf, on="Company")
carsDf

  Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160